name: PR Changelog Add
on:
  pull_request:
    types:
    - opened
    - edited
    - synchronized
    - labeled
    - unlabeled
jobs:
  check_pr_size:
    runs-on: ubuntu-latest
    steps:
    - uses: Guzzler/gh-changelog@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
