# .github/workflows/release.yml
name: Release

on:
  pull_request:
    types: closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v1.2.0
        with:
          github-token: ${{ secrets.github_token }}
          git-message: 'chore(release): {version}'
          preset: 'angular'
          tag-prefix: ''
          output-file: 'CHANGELOG.md'
          changelog-release-count: 5
#      - name: Tag
#        uses: K-Phoen/semver-release-action@master
#        with:
#          release_branch: master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
